### ISSUE TITLE
background color mask my code highlight

### ISSUE THREAD

**Issue by ginus** [smashwilson/merge-conflicts#118]
I use monokai syntax theme, you background color make it unreadable, I suggest that you could use border-color style.

**Comment by smashwilson** [comment]
@ginus I actually derive everything from the `ui-site-color` Less constants to keep the coloring as theme-agnostic as possible, but it doesn't always work. Naturally, I can't ensure that everything looks good (or even legible) on *all* themes.

If the theme you prefer doesn't play nicely, though, you can actually tweak it however you like by adding [rules to your custom stylesheet](https://atom.io/docs/v0.190.0/using-atom-basic-customization#style-tweaks) like so:

```less
atom-text-editor.conflicted::shadow {
  // Style the editor lines for "our" sides of conflicts
  .line.conflict-ours {
    background: #f88;
  }

  // Style the editor lines for "their" sides of conflicts
  .line.conflict-theirs {
    background: #88f;
  }
}

atom-overlay {
  // Style the "our changes" control overlay
  .side.ours {
    background: red;
  }

  // Style the navigation control separator
  .navigation {
    background: #ccc;
  }

  // Style the "their changes" control overlay
  .side.theirs {
    background: blue;
  }
}

```
