### ISSUE TITLE
Conflict header overlay positioning bug

### ISSUE THREAD

**Issue by simonlayfield** [smashwilson/merge-conflicts#188]
The conflict headers overlay the list of conflicts when scrolling.

![atom-merge-issue](https://cloud.githubusercontent.com/assets/2576361/10776780/b46083ea-7d68-11e5-8700-96dbb18964e6.gif)

**Comment by smashwilson** [comment]
Hmm, it isn't doing this for me:

![screen shot 2015-11-02 at 3 31 17 pm](https://cloud.githubusercontent.com/assets/17565/10893446/c8facf1a-8176-11e5-88a1-0a5d1bbb12b2.jpeg)

What themes were you using?

The version of Atom may effect this as well, if the z-index of overlay decorations was changed in core somehow. Once I publish 1.3.7, can you confirm that this is still happening on 1.1.0?

**Comment by hughker** [comment]
@smashwilson this just happened to me too…
`atom v1.1.0`
`merge-conflicts v1.3.7`
`Theme: Atom Light`
`Syntax: Solarized Light`

![screen shot 2015-11-03 at 12 22 08](https://cloud.githubusercontent.com/assets/3992387/10915899/d428b1bc-8226-11e5-91b4-a015c1b664ba.png)

If you need any other info, just let me know.

**Comment by simonlayfield** [comment]
Hey @smashwilson - sure.

This is still happening for me. I'm using:

Atom v1.1.0
Merge Conflicts v1.3.7
Theme: One Dark
Syntax: One Dark

**Comment by maxkazar** [comment]
Add into atom styles.less file:

```less
atom-text-editor {
  overflow: hidden;
}
```

It helps me.

**Comment by thibauds** [comment]
I've the same issue with :
Atom v1.2.4
Merge Conflicts v1.3.7
Theme: One Dark
Syntax: One Dark

**Comment by bhtruong93** [comment]
Thanks @maxkazar. In case anybody can't get to styles.less, it's in preferences -> config folder -> styles.less, and add the snippet that he posted.

**Comment by andersryanc** [comment]
same thing is happening for me, it's overlapping everything

![screen shot 2016-01-05 at 2 48 49 pm](https://cloud.githubusercontent.com/assets/689046/12209112/e1afe2e8-b605-11e5-9729-07834431bf22.png)

**Comment by andersryanc** [comment]
The overflow trick helps, but still looks a little odd when only parts of the UI overlap the line numbers

![screen shot 2016-01-08 at 12 55 10 pm](https://cloud.githubusercontent.com/assets/689046/12209365/38d11bae-b607-11e5-9e98-95a49d20bba7.png)

**Comment by bhtruong93** [comment]
Can you post your styles.less file?

**Comment by andersryanc** [comment]
I had to add "atom-text-editor" to line 15 (probably could have just replaced the class really - my styles file must be outdated)

```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

atom-text-editor, .atom-text-editor {
  overflow: hidden;
}

.atom-text-editor::shadow .cursor {

}

/* !- Taken from Seti-UI */
.icons(@icons) when (@icons = true) {
  @import "styles/icons";
}
/*
 * Set below to false to not import Seti-UI icons.
 * Requries View -> Reload after changing value.
 * Mainly to use with file-icons package.
*/
.icons(false);
```

**Comment by bhtruong93** [comment]
I don't think there's anything wrong with your stylesheet.  What's also odd is that your issue is a bit different from the previous ones.  Yours is off in the x-direction, but the 'fix' seemed to have remedied the y-direction.
:\

```css
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}

atom-text-editor {
  overflow: hidden;
}
```
